# Generated by Django 3.2.6 on 2021-08-26 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimun', models.IntegerField()),
                ('amount_per_package', models.IntegerField(verbose_name='amount-per-package')),
                ('max_availability', models.IntegerField(verbose_name='max-avaiability')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produto', models.IntegerField()),
                ('id_carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.carrinho')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.produto')),
            ],
        ),
    ]
